name: AntiVillagerLag
version: '${project.version}'
main: loyfael.antiVillagerLag.AntiVillagerLag
api-version: '1.20'
authors: [ RebelMythik, CaveRaider ]
description: Bonk Villagers

commands:
  avlreload:
    description: "Reloads the AVL plugin"
    usage: "/avlreload"
    permission: avl.reload
  avloptimize:
    description: "Will optimize all villagers within a configurable radius by renaming them"
    usage: "/avloptimize"
    permission: avl.optimize
  avlunoptimize:
    description: "Will unoptimize all villagers within a configurable radius by renaming them"
    usage: "/avlunoptimize"
    permission: avl.unoptimize
  avlremove:
    description: "Will remove all changes done by the plugin server wide"
    usage: "/avlremove"
    permission: avl.remove
  avlstatus:
    description: "Shows detailed status report of villagers in the area"
    usage: "/avlstatus [radius]"
    permission: avl.status
  avlinfo:
    description: "Shows information about the AntiVillagerLag plugin"
    usage: "/avlinfo"
    permission: avl.info
  mending:
    description: "Gestion des trades avec Mending"
    usage: "/mending [clear|status|toggle]"
    permission: antivillagerlag.mending

permissions:
  avl.cooldown.bypass:
    default: false
  avl.message.nextrestock:
    default: true
  avl.restockcooldown.bypass:
    default: false
  avl.notify.update:
    default: op
  avl.info:
    default: true
  antivillagerlag.mending:
    default: op
    description: "Permission pour gérer les trades avec Mending"
